<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = "12345678";
//      DB::statement('SET FOREIGN_KEY_CHECKS = 0');

        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'name' => 'Nawa Hinako',
                'email' => 'hi8nawa@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => null,
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2021-10-01')->format('Y-m-d'),
                User::PAID_OFF => 10.5,
                'status' => 1,
            ],
            [
                'name' => 'Kohei Ikeda',
                'email' => 'i.kohei2323@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => null,
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2020-12-01')->format('Y-m-d'),
                User::PAID_OFF => 27,
                'status' => 1,
            ],
            [
                'name' => 'Takaba Moeko',
                'email' => 'takaba.veho@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => null,
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2022-01-05')->format('Y-m-d'),
                User::PAID_OFF => 5.5,
                'status' => 1,
            ],
            [
                'name' => 'Vũ Anh Thư',
                'email' => 'thu.vu@veho-works.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1997-07-23')->format('Y-m-d'),
                User::ADDRESS => '194 Đội Cấn, Ba Đình, Hà Nội',
                User::TELEPHONE => '0981646094',
                User::SLACK_ID => 'UPE59LPHU',
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2019-10-01')->format('Y-m-d'),
                User::PAID_OFF => 4.5,
                'status' => 1,
            ],
            [
                'name' => 'Phạm Thị Trang',
                'email' => 'phamthitrang290@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1990-02-28')->format('Y-m-d'),
                User::ADDRESS => '79 Dương Quảng Hàm, Cầu Giấy, Hà Nội',
                User::TELEPHONE => '0966998390',
                User::SLACK_ID => 'U01TRJYCSKY',
                User::SKYPE_ID => 'live:phamthitrang290',
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-04-12')->format('Y-m-d'),
                User::PAID_OFF => 8.5,
                'status' => 1,
            ],
            [
                'name' => 'Đinh Thị Vững',
                'email' => 'dbacninh99@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => 'U04TK07SCUF',
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-03-15')->format('Y-m-d'),
                User::PAID_OFF => 5,
                'status' => 1,
            ],
            [
                'name' => 'Đỗ Xuân Vững',
                'email' => 'vungdoxuankthd@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1997-07-03')->format('Y-m-d'),
                User::ADDRESS => 'số 07, ngõ 66 Dịch Vọng Hậu, Cầu Giấy, HN',
                User::TELEPHONE => '0981007340',
                User::SLACK_ID => 'U01AP0JSKFX',
                User::SKYPE_ID => 'live:79ccdf18f1c5bace',
                User::GITHUB_ID => '46949214',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2020-09-16')->format('Y-m-d'),
                User::PAID_OFF => 23,
                'status' => 1,
            ],
            [
                'name' => 'Mai Văn Tuế',
                'email' => 'maivantue29@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1994-09-29')->format('Y-m-d'),
                User::ADDRESS => '77/47/28 Đường Xuân La, Tây Hồ,Hà Nội',
                User::TELEPHONE => '0339429892',
                User::SLACK_ID => 'U04R0T6TS3A',
                User::SKYPE_ID => 'live:maivantue29',
                User::GITHUB_ID => '44012114',
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2023-02-20')->format('Y-m-d'),
                User::PAID_OFF => 5,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Trọng Huy',
                'email' => 'nguyentronghuy22061998@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1998-02-04')->format('Y-m-d'),
                User::ADDRESS => 'Bích Hoà, Thanh Oai, Hà Nội',
                User::TELEPHONE => '0342059090',
                User::SLACK_ID => 'U042WBBQZM1',
                User::SKYPE_ID => 'live:.cid.6c14312a12f18ab5',
                User::GITHUB_ID => '113874560',
                User::ENTRY_DATE => Carbon::parse('2022-09-19')->format('Y-m-d'),
                User::PAID_OFF => 8.5,
                User::VIAM_USER_ID => 2,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Trung Nguyên',
                'email' => 'nguyentrungnguyenth14@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1996-02-22')->format('Y-m-d'),
                User::ADDRESS => '173/69/ Hoàng Hoa Thám, Ba Đình, Hà Nội',
                User::TELEPHONE => '0988360149',
                User::SLACK_ID => 'U04M147LNMD',
                User::SKYPE_ID => 'live:nguyentrungnguyenth14_1',
                User::GITHUB_ID => '31590813',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-02-01')->format('Y-m-d'),
                User::PAID_OFF => 2,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Văn Nguyên',
                'email' => 'nguyenvn099@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1989-11-30')->format('Y-m-d'),
                User::ADDRESS => 'số 28 19/28 Trần Quang Diệu, Ô chợ Dừa, Đống Đa, Hà Nội',
                User::TELEPHONE => '0975645153',
                User::SLACK_ID => 'U0410L03BTL',
                User::SKYPE_ID => 'live:nguyenvn099',
                User::GITHUB_ID => '18542251',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2022-09-01')->format('Y-m-d'),
                User::PAID_OFF => 9,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Thị Ngân',
                'email' => 'ngannguyendt2haui@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1994-10-06')->format('Y-m-d'),
                User::ADDRESS => 'Thôn Đông,Phú Minh,Sóc Sơn, Hà Nội',
                User::TELEPHONE => '0359756191',
                User::SLACK_ID => 'U02746QF3LZ',
                User::SKYPE_ID => 'live:.cid.fc94dd91e77d3b48',
                User::GITHUB_ID => '53175156',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-07-01')->format('Y-m-d'),
                User::PAID_OFF => 17.5,
                'status' => 1,
            ],
            [
                'name' => 'Ngô Hồng Sơn',
                'email' => 'ngoson919597@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1997-08-22')->format('Y-m-d'),
                User::ADDRESS => '144 phố Ba Thá, Xã Viên An, Huyện Ứng Hoà, Hà Nội',
                User::TELEPHONE => '392999601',
                User::SLACK_ID => 'U021E6799BK',
                User::SKYPE_ID => 'live:.cid.287e571901df5795',
                User::GITHUB_ID => '70569275',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2022-04-01')->format('Y-m-d'),
                User::PAID_OFF => 0,
                'status' => 1,
            ],
            [
                'name' => 'Lý Văn Phương',
                'email' => 'phuong.codeunited@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => 'U02749EEMB3',
                User::SKYPE_ID => null,
                User::GITHUB_ID => '16416312',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-06-01')->format('Y-m-d'),
                User::PAID_OFF => 15,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Tùng Bách',
                'email' => 'nguyentungbachholo@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1998-06-02')->format('Y-m-d'),
                User::ADDRESS => '119B Sân bóng Đỗ Lợi, hẻm 29 ngách 28, ngõ Văn Hương, Tôn Đức Thắng, Hà Nội',
                User::TELEPHONE => '0337297070',
                User::SLACK_ID => 'U059ZNNRSHM',
                User::SKYPE_ID => 'live:.cid.1dfa6370ba47f4f7',
                User::GITHUB_ID => '78024702',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-08-01')->format('Y-m-d'),
                User::PAID_OFF => 4,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Trung Thành',
                'email' => 'trungthanh2388@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1988-03-02')->format('Y-m-d'),
                User::ADDRESS => 'Nguyên Xá - Minh Khai - Bắc Từ Liêm',
                User::TELEPHONE => '0981118282',
                User::SLACK_ID => 'U04CT6KTFNK',
                User::SKYPE_ID => null,
                User::GITHUB_ID => '103564824',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2022-12-01')->format('Y-m-d'),
                User::PAID_OFF => 5.5,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Hải Yến',
                'email' => 'haiyentp.1204@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2000-10-01')->format('Y-m-d'),
                User::ADDRESS => 'số 17 ngõ 123 Yên Xá Tân Triều Thanh Trì Hà Nội',
                User::TELEPHONE => '0969781294',
                User::SLACK_ID => 'U04QDLKMTB6',
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2023-02-20')->format('Y-m-d'),
                User::PAID_OFF => 0,
                'status' => 1,
            ],
            [
                'name' => 'Vũ Thị Hoa',
                'email' => 'vuhoa11052000@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2000-05-11')->format('Y-m-d'),
                User::ADDRESS => 'ngõ 67 Văn Cao, Ba Đinh, Hà Nội',
                User::TELEPHONE => '0869962391',
                User::SLACK_ID => 'U04QDLKMTB6',
                User::SKYPE_ID => 'live:.cid.b7e3541bc0ab4d3e',
                User::GITHUB_ID => '72261975',
                User::VIAM_USER_ID => 1,
                User::ENTRY_DATE => Carbon::parse('2023-05-01')->format('Y-m-d'),
                User::PAID_OFF => 4,
                'status' => 1,
            ],
            [
                'name' => 'Ngô Tuấn Cường',
                'email' => 'tuancuongth88@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1991-12-16')->format('Y-m-d'),
                User::ADDRESS => 'số 7 ngõ 93 Đại Linh, Trung Văn, Nam Từ Liêm, Hà Nội',
                User::TELEPHONE => '0358002108',
                User::SLACK_ID => 'U01VA7CG59T',
                User::SKYPE_ID => 'live:tuancuongth88',
                User::GITHUB_ID => '15207537',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-04-26')->format('Y-m-d'),
                User::PAID_OFF => 14,
                'status' => 1,
            ],
            [
                'name' => 'Phạm Tuấn Kiệt',
                'email' => 'ptkit1.0@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1990-04-01')->format('Y-m-d'),
                User::ADDRESS => '266 Đội Cấn - Liễu Giai - Ba Đình - Hà Nội',
                User::TELEPHONE => '0988949703',
                User::SLACK_ID => 'U02CNKXN3FF',
                User::SKYPE_ID => null,
                User::GITHUB_ID => '41821404',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2022-04-12')->format('Y-m-d'),
                User::PAID_OFF => 14.5,
                'status' => 1,
            ],
            [
                'name' => 'Hà Thái Việt',
                'email' => 'hathaiviet411@gmai.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2000-11-04')->format('Y-m-d'),
                User::ADDRESS => '46/514 Thuy Khue, Tay Ho, Ha Noi',
                User::TELEPHONE => '0342883925',
                User::SLACK_ID => 'U01JVDH9W7J',
                User::SKYPE_ID => 'live:.cid.4ead34a6d8552651',
                User::GITHUB_ID => '44861478',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-03-18')->format('Y-m-d'),
                User::PAID_OFF => 0,
                'status' => 1,
            ],
            [
                'name' => 'Tạ Thị Thủy',
                'email' => 'tathithuyvn89@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => null,
                User::ADDRESS => null,
                User::TELEPHONE => null,
                User::SLACK_ID => 'U01BU7F0X6U',
                User::SKYPE_ID => null,
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2020-09-23')->format('Y-m-d'),
                User::PAID_OFF => 9.5,
                'status' => 1,
            ],
            [
                'name' => 'Đồng Việt Long',
                'email' => 'dongvietlong123@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2001-07-13')->format('Y-m-d'),
                User::ADDRESS => 'Nhà 26a, Hẻm 193/220/77 Đường Phú Diễn, Làng Phú Diễn, Bắc Từ Liêm, Hà Nội',
                User::TELEPHONE => '0969593044',
                User::SLACK_ID => 'U04QB3F77H9',
                User::SKYPE_ID => null,
                User::GITHUB_ID => '90855047',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-05-01')->format('Y-m-d'),
                User::PAID_OFF => 2.5,
                'status' => 1,
            ],
            [
                'name' => 'Hoàng Trung Nam',
                'email' => 'hoangtrungnam0000@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2001-04-29')->format('Y-m-d'),
                User::ADDRESS => 'Ngách 1002/5 Đường Láng Phường Láng Thượng, Quận Đống Đa, Hà Nội',
                User::TELEPHONE => '0988324977',
                User::SLACK_ID => 'U05FF90BS3X',
                User::SKYPE_ID => null,
                User::GITHUB_ID => '57910461',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-07-05')->format('Y-m-d'),
                User::PAID_OFF => 3,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Đức Thủ',
                'email' => 'thubkit.hut@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1989-11-10')->format('Y-m-d'),
                User::ADDRESS => 'Phú Lãm - Hà Đông - Hà Nội',
                User::TELEPHONE => '0984113136',
                User::SLACK_ID => 'U01GKGQUU02',
                User::SKYPE_ID => 'megamind1110',
                User::GITHUB_ID => '136047326',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2021-01-01')->format('Y-m-d'),
                User::PAID_OFF => 0,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Duy Khánh',
                'email' => 'Duykhanhnw@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('1996-01-04')->format('Y-m-d'),
                User::ADDRESS => '22A15 Đầm Trấu, Bạch Đằng, Hai Bà Trưng, Hà Nôị',
                User::TELEPHONE => '0374100603',
                User::SLACK_ID => 'U0614VDDSJH',
                User::SKYPE_ID => 'live:ndkhanh1996',
                User::GITHUB_ID => '148027909',
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => null,
                User::PAID_OFF => 0,
                'status' => 1,
            ],
            [
                'name' => 'Nguyễn Thị Phương Hoa',
                'email' => 'ntphoa0209@gmail.com',
                'password' => Hash::make($password),
                User::BIRTHDAY => Carbon::parse('2001-09-02')->format('Y-m-d'),
                User::ADDRESS => '26/8 Tân Xuân, Xuân Đỉnh, Bắc Từ Liêm, Hà Nội ',
                User::TELEPHONE => '0985005942',
                User::SLACK_ID => 'U063Z0QD9BN',
                User::SKYPE_ID => 'live:.cid.9dcacec52444c6d8',
                User::GITHUB_ID => null,
                User::VIAM_USER_ID => 2,
                User::ENTRY_DATE => Carbon::parse('2023-11-02')->format('Y-m-d'),
                User::PAID_OFF => 0,
                'status' => 1,
            ],
        ]);
//      DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}

