[program:v-face-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --sleep=1 --tries=1
autostart=true
autorestart=true
user=ec2-user
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/v-face/storage/logs/worker.log
