<?php


namespace Http\Controllers;


use App\Http\Controllers\Api\DigitacoFileController;
use App\Http\Requests\DigitacoFileRequest;
use App\Models\DigitacoFile;
use App\Repositories\Contracts\DigitacoFileRepositoryI;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Repository\DigitacoFileRepository;
use Tests\TestCase;
use Mockery as m;

class DigitacoTest extends TestCase
{
  protected $data;
  /**
   * @var DigitacoFileController
   */
  protected $digitacoController;
  protected $digitacoRepository;
  protected $digitacoRequest;
  use WithFaker;

  public function setUp(): void
  {
    $app = new Application();
    $digitacoRepo = new DigitacoFileRepository($app);
    $this->afterApplicationCreated(function () use ($digitacoRepo) {
      $this->digitacoRepository = m::mock($digitacoRepo)->makePartial();
      $this->digitacoController = new DigitacoFileController($this->app->instance(DigitacoFileRepositoryI::class, $this->digitacoRepository));
    });
    $this->digitacoRequest = new DigitacoFileRequest();

    parent::setUp();
  }

  public function tearDown(): void
  {
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  ////    Test OK
  public function testDataManagementList()
  {
    Artisan::call('test:getmail');
    $response = $this->digitacoController->index($this->digitacoRequest);
    $this->assertEquals(200,$response->getStatusCode());
  }


  public function testDataManagementDetail()
  {
    Artisan::call('test:getmail');
    $digitacofile = DigitacoFile::orderBy('id')->first();
    $response = $this->digitacoController->detail($digitacofile->id, 'point',$this->digitacoRequest);
    $this->assertEquals(200,$response->getStatusCode());
  }
}
