<?php


namespace Http\Controllers;


use App\Http\Controllers\Api\DataManagementController;
use App\Http\Controllers\Api\EmployeeController;
use App\Http\Controllers\Api\EnrollmentController;
use App\Http\Requests\DataManagementRequest;
use App\Http\Requests\EnrollmentRequest;
use App\Models\DataManagement;
use App\Models\Enrollment;
use App\Repositories\Contracts\DataManagementRepositoryInterface;
use App\Repositories\Contracts\EmployeeRepositoryInterface;
use App\Repositories\Contracts\EnrollmentRepositoryInterface;
use App\Repositories\EmployeeRepository;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use phpDocumentor\Reflection\Types\Object_;
use Repository\ConfigRangeRepository;
use Repository\DataManagementRepository;
use Repository\EnrollmentRepository;
use Repository\RiskScoreRepository;
use Tests\TestCase;
use Illuminate\Support\Facades\Facade;
use Faker\Factory as Faker;
use Illuminate\Foundation\Application;
use Illuminate\Http\UploadedFile;
use Mockery as m;


class EmployeeTest extends TestCase
{
  protected $data;
  protected $param;
  protected $dataRepository;
  /**
   * @var EmployeeController
   */
  protected $dataManagementController;
  protected $dataManagementRequest;
  protected $dataManagementRepository;
  protected $repository;
  protected $request;
  //create false
  protected $data_create_false;

  use WithFaker;

  public function setUp(): void
  {
    $app = new Application();
    $riskRepository = new RiskScoreRepository($app);
    $dataManagementRepository = new EmployeeRepository($app, $riskRepository);

    $this->afterApplicationCreated(function () use ($dataManagementRepository) {
      $this->dataManagementRepository = m::mock($dataManagementRepository)->makePartial();
      $this->dataManagementController = new EmployeeController(
        $this->app->instance(EmployeeRepositoryInterface::class, $this->dataManagementRepository)
      );
    });

//    parent::setUp(); // TODO: Change the autogenerated stub
//    Facade::clearResolvedInstances();
//    $this->faker = Faker::create();
    $this->dataManagementRequest = new dataManagementRequest();
    $this->faker = Faker::create();
    $this->request = new Request();
    // chuẩn bị dữ liệu test
    $this->data['data'] = [
      ['employee_code' => '1111-1111-2227',
        'employee_name' => 'aaaaa',
        'joining_age_company' => 25,
        'date_joining_company' => '2020/10/10',
        'date_out_company' => '2021/10/10',
        'spouse' => 1,
        'dependents' => 5,
        'worked_year' => 1,
        'final_education' => 5,
        'shortest_service' => 1,
        'total_worked' => 1,
        'company_branch' => '管理本部',
        //      'created_by'=>  Enrollment::first()->id,
        'created_by' => 1,
        'updated_by' => 1,
      ],
      ['employee_code' => '1111-1111-2228',
        'employee_name' => 'aaaaa',
        'joining_age_company' => 25,
        'date_joining_company' => '2020/10/10',
        'date_out_company' => '2021/10/10',
        'spouse' => 1,
        'dependents' => 5,
        'worked_year' => 1,
        'final_education' => 5,
        'shortest_service' => 1,
        'total_worked' => 1,
        'company_branch' => '管理本部',
        //      'created_by'=>  Enrollment::first()->id,
        'created_by' => 1,
        'updated_by' => 1,
      ]
    ];

    $this->data_create_false['data'] = [
      ['employee_code' => '',
        'staffs_name' => 'aaaaa',
        'joining_age_company' => 25,
        'date_joining_company' => '2020/10/10',
        'date_out_company' => '2021/10-/10',
        'spouse' => 1,
        'dependents' => 5,
        'worked_year' => 1,
        'final_education' => 5,
        'shortest_service' => 1,
        'total_worked' => 1,
        'company_branch' => '管理本部',
        'created_by' => 1,
        'updated_by' => 1,
      ],
      ['employee_code' => '',
        'staffs_name' => 'aaaaa',
        'joining_age_company' => 25,
        'date_joining_company' => '2020/10/10',
        'date_out_company' => '2021/10/10',
        'spouse' => 1,
        'dependents' => 5,
        'worked_year' => 1,
        'final_education' => 5,
        'shortest_service' => 1,
        'total_worked' => 1,
        'company_branch' => '管理本部',
        'created_by' => 1,
        'updated_by' => 1,
      ]
    ];
//    $encodedSku = json_encode($data);
//    $this -> data = json_encode($data);
//    $this->param = [
//      'staffs_name'=> 'hakata',
//      'joining_age_company'=> 25,
//    ];
    parent::setUp();
//    $app = Application::getInstance();
//    $this->dataRepository = new DataManagementRepository($app);
  }

  public function tearDown(): void
  {
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

//  public function testDataManagementCreate()
//  {
//    // Gọi hàm tạo
//    $request = new DataManagementRequest();
//    $request->merge($this->data);
//    // $request->header()
//    $response = $this->dataRepository->create($request->toArray());
//    dd($response);
//  }
//
//  public function testDataManagementShowID()
//  {
//    // Gọi hàm tạo
//    $request = new DataManagementRequest();
//    $request->merge($this->data);
//    // $request->header()
//    $data = $this->dataRepository->create($request->toArray());
//    $response = $this->dataRepository->find($data->id);
//    dd($response);
//  }
//
//  public function testDataManagementUpdate()
//  {
//    // Gọi hàm tạo
//    $request = new DataManagementRequest();
//    $request->merge($this->data);
//    // $request->header()
//    $data = $this->dataRepository->create($request->toArray());
//    $response = $this->dataRepository->update($request->toArray(), $data->id);
//    dd($response);
//  }
//
//  public function testDataManagementRemove()
//  {
//    // Gọi hàm tạo
//    $request = new DataManagementRequest();
//    $request->merge($this->data);
//    // $request->header()
//    $data = $this->dataRepository->create($request->toArray());
//    $response = $this->dataRepository->delete($data->id);
//    dd($response);
//  }

  public function testThatItImportsTheUploadedFileFalse()
  {
    $this->dataManagementRequest->merge($this->data_create_false);
    $response = $this->dataManagementController->store($this->dataManagementRequest);
    $this->assertNotEquals(false, $response);
  }

  public function testThatItImportsTheUploadedFileSuccess()
  {
//    $file = new UploadedFile(
//      base_path('tests\FileTestData\Data_import.csv'),
//      'Data_import.csv',
//      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
//      null,
//      true
//    );
//    $array=[
//      'data_file'=>$file
//    ];
//    $data = json_decode($request->data);
//    $encodedSku = json_encode($data);
//    $this->dataManagementRequest->merge(["data"=> $this->data]);
    $this->dataManagementRequest->merge($this->data);
    //dd($this->dataManagementRequest);
    $response = $this->dataManagementController->store($this->dataManagementRequest);
    $this->assertNotEquals(false, $response);
//    $this->assertTrue(is_array($response));
//    $this->assertTrue('success', $response['status']);
//    $this->assertNotEquals(200,"The Status code is not matched", $response);
  }

  public function testDataManagementList()
  {
//    $request = new DataManagementRequest();
//    $request->merge($this->data);
//    $data = $this->dataRepository->createtest($request->toArray());
//    $response = $this->dataRepository->get();
    $this->dataManagementRequest->merge($this->data);
    $this->dataManagementController->store($this->dataManagementRequest);
    $response = $this->dataManagementController->index($this->dataManagementRequest);
//    dd($response);
    $this->assertNotEquals(false, $response);
  }

  public function testGetAllEmployee()
  {
    $this->dataManagementRequest->merge($this->data);
    $this->dataManagementController->store($this->dataManagementRequest);
    $response = $this->dataManagementController->getAll($this->dataManagementRequest);
    $this->assertNotEquals(false, $response);
  }

  public function testEmployeeDetail()
  {
    $this->request->merge($this->data);
    $response=$this->dataManagementController->detail($this->request);
    $this->assertNotEquals(false, $response);
  }
}
