<?php


namespace Http\Controllers;


use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class GetMailTest extends TestCase
{
  public function setUp(): void
  {
    parent::setUp();
  }

  public function tearDown(): void
  {
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  public function testGetMail()
  {
    Artisan::call('GetMail:import');
    $this->assertTrue(true);
  }

  public function testSendData()
  {
    Artisan::call('DigitacoFile:sendFile');
    $this->assertTrue(true);
  }
}
