<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Models\ImageFace;
use App\Models\User;
use App\Repositories\Contracts\ImageFaceRepositoryInterface;
use Carbon\Carbon;
use Helper\ResponseService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;

class ImageFaceRepository extends BaseRepository implements ImageFaceRepositoryInterface
{

     public function __construct(Application $app)
     {
         parent::__construct($app);

     }

    /**
       * Instantiate model
       *
       * @param ImageFace $model
       */

    public function model()
    {
        return ImageFace::class;
    }

    public function createImageFace(array $attributes)
    {
      // Kiểm tra id user này có tồn tại không
      $user = User::find($attributes['user_id']);

      if ($user == null){
        return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.image_face.user_id_not_found'), trans('api.image_face.user_id_not_found'));
      }
      $attributes['created_at'] = Carbon::now();

      return ResponseService::responseJson(Response::HTTP_OK,parent::create($attributes)); // TODO: Change the autogenerated stub
    }

    public function deleteImageFace($id){
      DB::table('image_faces')->where('id', $id)->delete();
    }
}
