<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Http\Resources\UserResource;
use App\Models\ArrivingReport;
use App\Models\ImageFace;
use App\Models\User;
use App\Repositories\Contracts\ImageFaceRepositoryInterface;
use Aws\Rekognition\Exception\RekognitionException;
use Aws\Rekognition\RekognitionClient;
use Carbon\Carbon;
use DateTime;
use Exception;
use Helper\ResponseService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use Tymon\JWTAuth\Facades\JWTAuth;

class ImageFaceRepository extends BaseRepository implements ImageFaceRepositoryInterface
{

     public function __construct(Application $app)
     {
         parent::__construct($app);

     }

    /**
       * Instantiate model
       *
       * @param ImageFace $model
       */

    public function model()
    {
        return ImageFace::class;
    }

    public function findByField($field, $value = null, $columns = ['*'])
    {
      $result = parent::findByField($field, $value, $columns);

      // Kiểm tra nếu có kết quả trả về
      if ($result) {
        // Lặp qua từng phần tử trong kết quả
        foreach ($result as $item) {
          // Thêm đoạn "https://v-face.s3.amazonaws.com/" vào trường file
          $item->file = config('services.aws.urlImage') . $item->file;
        }
      }

      return $result; // TODO: Change the autogenerated stub
    }

  public function createImageFace(array $attributes)
    {
      // Kiểm tra id user này có tồn tại không
      $user = User::find($attributes['user_id']);

      $configOptions = [
        'region'    => config('services.aws.AWS_DEFAULT_REGION'),
        'version'   => 'latest',
        'credentials' => [
          'key' => config('services.aws.AWS_ACCESS_KEY_ID'), // Thay thế bằng access key của bạn
          'secret' => config('services.aws.AWS_SECRET_ACCESS_KEY'), // Thay thế bằng secret access key của bạn
        ]
      ];

      if ($user == null){
        return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.image_face.user_id_not_found'), trans('api.image_face.user_id_not_found'));
      }
      $attributes['created_at'] = Carbon::now();

      $arrayAddImage = [];
      try {
        if (request()->hasFile('file')) {
          $files = request()->file('file');
          $rekognitionClient = new RekognitionClient($configOptions);
          // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
          foreach ($files as $file){
            $result = $rekognitionClient->detectFaces(
              [
                'Image' => [
                  'Bytes' => file_get_contents($file),
                ],
              ],
            );
            // Ảnh chỉ được phép một người
            if (count($result['FaceDetails']) != 1 ){
              ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
            }
          }

          // Xác nhận lưu ảnh vào bucket
          foreach ($files as $file){
            $name = time() . $file->getClientOriginalName();
//          $filePath = 'images/' . $name;
            $filePath = $attributes['type'].'/'. $name;
            Storage::disk('s3')->put($filePath, file_get_contents($file));
            $attributes['file'] = $filePath;

            // Xác nhận lưu điểm ảnh nhận dạng khuôn mặt
            $resultFaceCollection = $rekognitionClient->indexFaces(
              [
                'CollectionId' => $attributes['type'],
                'Image' => [
                  'Bytes' => file_get_contents($file),
                ],
              ]
            );
            $attributes['face_rekognition_id'] = $resultFaceCollection->get('FaceRecords')[0]['Face']['FaceId'];
            $arrayAddImage[] = parent::create($attributes);
          }
        }
      } catch (Exception $ex){
        ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR,$ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
      }

      return ResponseService::responseJson(Response::HTTP_OK,$arrayAddImage); // TODO: Change the autogenerated stub
    }

    public function deleteImageFace($id){
      $deleteImage = $this->model->find($id);
      if (!$deleteImage){
        return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.image_face.id_not_found'), trans('api.image_face.id_not_found'));
      } else{
        // Xóa ảnh trong bucket
//        $imagePath = explode(config('services.aws.urlImage'), $deleteImage->file)['1'];
        Storage::disk('s3')->delete($deleteImage->file);

        // Xóa ảnh trong collection
        $options = [
          'region'    => config('services.aws.AWS_DEFAULT_REGION'),
          'version'   => 'latest',
          'credentials' => [
            'key' => config('services.aws.AWS_ACCESS_KEY_ID'), // Thay thế bằng access key của bạn
            'secret' => config('services.aws.AWS_SECRET_ACCESS_KEY'), // Thay thế bằng secret access key của bạn
          ]
        ];
        $rekognitionClient = new RekognitionClient($options);
        try {
          $rekognitionClient->deleteFaces(
            [
              'CollectionId' => $deleteImage->type,
              'FaceIds' => [$deleteImage->face_rekognition_id],
            ]
          );

        } catch (RekognitionException $ex){
          ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR,$ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
        }

        DB::table('image_faces')->where('id', $id)->delete();
        return ResponseService::responseJson(200, null, trans('messages.mes.delete_success'));
      }
    }

    public function compareFace(array $attributes){
      $options = [
        'region'    => config('services.aws.AWS_DEFAULT_REGION'),
        'version'   => 'latest',
        'credentials' => [
          'key' => config('services.aws.AWS_ACCESS_KEY_ID'), // Thay thế bằng access key của bạn
          'secret' => config('services.aws.AWS_SECRET_ACCESS_KEY'), // Thay thế bằng secret access key của bạn
        ]
      ];

      $rekognitionClient = new RekognitionClient($options);

      if (request()->hasFile('file')){
        // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
        $checkImageMustOne = $rekognitionClient->detectFaces(
          [
            'Image' => [
              'Bytes' => file_get_contents($attributes['file']),
            ],
          ],
        );
        // Ảnh chỉ được phép một người
        if (count($checkImageMustOne['FaceDetails']) != 1 ){
          ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
        }

        $result = [];
        try {
          $result = $rekognitionClient->searchFacesByImage(
            [
              'CollectionId' => "WithoutMask",
              'Image' => [
                'Bytes' => file_get_contents($attributes['file']),
              ],
            ]
          );
        } catch (RekognitionException $ex){
          // Nếu không có lỗi thì tìm kiếm trong Collection WithMask
          try {
            $result = $rekognitionClient->searchFacesByImage(
              [
                'CollectionId' => "WithMask",
                'Image' => [
                  'Bytes' => file_get_contents($attributes['file']),
                ],
              ]
            );
          } catch (RekognitionException $ex){
            return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR,$ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
          }
        }
      } else {
        // Chuyển đổi dữ liệu Base64 thành định dạng binary
        $imageData = $attributes['file'];

        // Loại bỏ phần khai báo định dạng ảnh
        $imageData = preg_replace('/^data:image\/\w+;base64,/', '', $imageData);

        // Giải mã chuỗi base64 thành dữ liệu binary
        $imageData = base64_decode($imageData);

        // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
        $checkImageMustOne = $rekognitionClient->detectFaces(
          [
            'Image' => [
              'Bytes' => $imageData,
            ],
          ],
        );
        // Ảnh chỉ được phép một người
        if (count($checkImageMustOne['FaceDetails']) != 1 ){
          ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
        }
        $result = [];
        try {
          $result = $rekognitionClient->searchFacesByImage(
            [
              'CollectionId' => "WithoutMask",
              'Image' => [
                'Bytes' => $imageData,
              ],
            ]
          );
        } catch (RekognitionException $ex) {
          // Nếu không có lỗi thì tìm kiếm trong Collection WithMask
          try {
            $result = $rekognitionClient->searchFacesByImage(
              [
                'CollectionId' => "WithMask",
                'Image' => [
                  'Bytes' => file_get_contents($attributes['file']),
                ],
              ]
            );
          } catch (RekognitionException $ex){
            return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR,$ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
          }
        }
      }
      if ($result->get("FaceMatches") == []){
        return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND,trans('api.image_face.face_compare_not_found'), trans('api.image_face.face_compare_not_found'));
      }
      $faceId = $result->get("FaceMatches")[0]["Face"]["FaceId"];
      $image = $this->model->where("face_rekognition_id",$faceId)->first();
      $user = User::find($image->user_id);

      if ($user == null){
        return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND,trans('api.user.login.false'));
      }

      // Kiểm tra ngày hôm nay in hay out đã check chưa?
      $dateTimeNow = new DateTime('now');
      // Kiểm tra nhân viên này hôm nay đã check in chưa?
      $arrivingIn_time = ArrivingReport::
      whereDate("in_time",$dateTimeNow->format('Y-m-d'))
        ->where("user_id",$user->id)
        ->first();

      // Kiểm tra nhân viên này hôm nay đã check out chưa?
      $arrivingOut_time = ArrivingReport::
      whereDate("out_time",$dateTimeNow->format('Y-m-d'))
        ->where("user_id",$user->id)
        ->first();
//        switch ($attributes['time']){
//          case 'in':
//            if ($arrivingIn_time){
//              return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.arriving_report.time_in_is_check'), trans('api.arriving_report.time_in_is_check'));
//            } else{
//              $arrivingIn_time = new ArrivingReport();
//              $arrivingIn_time->in_time = Carbon::now();
//              $arrivingIn_time->link_face_in = config('services.aws.urlImage').$image->file;
//              $arrivingIn_time->status = 1;
//              $arrivingIn_time->created_at = Carbon::now();
//              if (array_key_exists("registration_type",$attributes)){
//                $arrivingIn_time->registration_type = $attributes['registration_type'];
//              }
//              $arrivingIn_time->save();
//            }
//            break;
//          case 'out':
//            if ($arrivingIn_time == null){
//              return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.arriving_report.need_check_time_in'), trans('api.arriving_report.need_check_time_in'));
//            }
//            if ($arrivingOut_time){
//              return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.arriving_report.time_in_is_check'), trans('api.arriving_report.time_in_is_check'));
//            } else{
//              $arrivingOut_time = new ArrivingReport();
//              $arrivingOut_time->in_time = Carbon::now();
//              $arrivingOut_time->link_face_in = config('services.aws.urlImage').$image->file;
//              $arrivingOut_time->status = 1;
//              $arrivingOut_time->created_at = Carbon::now();
//              if (array_key_exists("registration_type",$attributes)){
//                $arrivingOut_time->registration_type = $attributes['registration_type'];
//              }
//              $arrivingOut_time->save();
//            }
//            break;
//        }
      try {
        $token = JWTAuth::fromUser($user);
        $user->jwt_active = $token;
        $user->save();
      } catch (Exception $ex) {
        return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR,$ex->getMessage());
      }

      return ResponseService::responseJson(200, [
        'access_token' => "Bearer " . $token,
        'profile' => new UserResource($user),
        'in_time' => $arrivingIn_time,
        'out_time' => $arrivingOut_time,
        'imageLink' => config('services.aws.urlImage') . $image->file
      ]);
    }

  public function checkImage(array $attributes)
  {
    $options = [
      'region' => config('services.aws.AWS_DEFAULT_REGION'),
      'version' => 'latest',
      'credentials' => [
        'key' => config('services.aws.AWS_ACCESS_KEY_ID'), // Thay thế bằng access key của bạn
        'secret' => config('services.aws.AWS_SECRET_ACCESS_KEY'), // Thay thế bằng secret access key của bạn
      ]
    ];

    $rekognitionClient = new RekognitionClient($options);

    try {
      // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
      $checkImageMustOne = $rekognitionClient->detectFaces(
        [
          'Image' => [
            'Bytes' => file_get_contents($attributes['file']),
          ],
        ],
      );
      // Ảnh chỉ được phép một người
      if (count($checkImageMustOne['FaceDetails']) != 1) {
        ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
      }
      return ResponseService::responseJson(200, [
        'checkImage' => count($checkImageMustOne['FaceDetails']) == 1,
      ]);
    } catch (Exception $ex) {
      return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getMessage());
    }
  }
}
