<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Helpers\UserSystemInfoHelper;
use App\Http\Resources\UserResource;
use App\Mail\NegativeStaffMail;
use App\Models\ArrivingReport;
use App\Models\BreakTime;
use App\Models\Emotion;
use App\Models\ImageFace;
use App\Models\User;
use App\Repositories\Contracts\EmotionRepositoryInterface;
use App\Repositories\Contracts\ImageFaceRepositoryInterface;
use Aws\Credentials\CredentialProvider;
use Aws\Rekognition\Exception\RekognitionException;
use Aws\Rekognition\RekognitionClient;
use Carbon\Carbon;
use DateTime;
use Exception;
use Helper\ResponseService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use Tymon\JWTAuth\Facades\JWTAuth;

class ImageFaceRepository extends BaseRepository implements ImageFaceRepositoryInterface
{

    public function __construct(Application $app)
    {
        parent::__construct($app);
    }

    /**
     * Instantiate model
     *
     * @param ImageFace $model
     */

    public function model()
    {
        return ImageFace::class;
    }

    private function configRekognitionClient()
    {
        if (!App::environment('local')) {
            // Tạo một đối tượng Credential Provider từ IAM Role
            $credentials = CredentialProvider::defaultProvider();

            // Cung cấp tùy chọn cấu hình cho RekognitionClient
            $config = [
                'version' => 'latest',
                'region' => 'ap-northeast-1', // Thay thế bằng khu vực của bạn
                'credentials' => $credentials,
            ];

            // Khởi tạo RekognitionClient với các tùy chọn cấu hình
            $rekognitionClient = new RekognitionClient($config);
        } else {
            $options = [
                'region' => config('services.aws.AWS_DEFAULT_REGION'),
                'version' => 'latest',
                'credentials' => [
                    'key' => config('services.aws.AWS_ACCESS_KEY_ID'), // Thay thế bằng access key của bạn
                    'secret' => config('services.aws.AWS_SECRET_ACCESS_KEY'), // Thay thế bằng secret access key của bạn
                ]
            ];
            $rekognitionClient = new RekognitionClient($options);
        }
        return $rekognitionClient;
    }

    public function findByField($field, $value = null, $columns = ['*'])
    {
        $result = parent::findByField($field, $value, $columns);

        // Kiểm tra nếu có kết quả trả về
        if ($result) {
            // Lặp qua từng phần tử trong kết quả
            foreach ($result as $item) {
                // Thêm đoạn "https://v-face.s3.amazonaws.com/" vào trường file
                $item->file = config('services.aws.urlImage') . $item->file;
            }
        }

        return $result; // TODO: Change the autogenerated stub
    }

    public function createImageFace(array $attributes)
    {
        // Kiểm tra id user này có tồn tại không
        $user = User::find($attributes['user_id']);

        if ($user == null) {
            return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.image_face.user_id_not_found'), trans('api.image_face.user_id_not_found'));
        }
        $attributes['created_at'] = Carbon::now();

        $arrayAddImage = [];
        try {
            if (request()->hasFile('file')) {
                $files = request()->file('file');
                $rekognitionClient = $this->configRekognitionClient();
                // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
                foreach ($files as $file) {
                    $result = $rekognitionClient->detectFaces(
                        [
                            'Image' => [
                                'Bytes' => file_get_contents($file),
                            ],
                        ]
                    );
                    // Ảnh chỉ được phép một người
                    if (count($result['FaceDetails']) != 1) {
                        ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
                    }
                }

                // Xác nhận lưu ảnh vào bucket
                foreach ($files as $file) {
                    $name = time() . $file->getClientOriginalName();
//          $filePath = 'images/' . $name;
                    $filePath = $attributes['type'] . '/' . $name;
                    Storage::disk('s3')->put($filePath, file_get_contents($file));
                    $attributes['file'] = $filePath;

                    // Xác nhận lưu điểm ảnh nhận dạng khuôn mặt
                    $resultFaceCollection = $rekognitionClient->indexFaces(
                        [
                            'CollectionId' => $attributes['type'],
                            'Image' => [
                                'Bytes' => file_get_contents($file),
                            ],
                        ]
                    );
                    $attributes['face_rekognition_id'] = $resultFaceCollection->get('FaceRecords')[0]['Face']['FaceId'];
                    $arrayAddImage[] = parent::create($attributes);
                }
            }
        } catch (Exception $ex) {
            ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
        }

        return ResponseService::responseJson(Response::HTTP_OK, $arrayAddImage); // TODO: Change the autogenerated stub
    }

    public function deleteImageFace($id)
    {
        $deleteImage = $this->model->find($id);
        if (!$deleteImage) {
            return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.id_not_found'), trans('api.image_face.id_not_found'));
        } else {
            // Xóa ảnh trong bucket
//        $imagePath = explode(config('services.aws.urlImage'), $deleteImage->file)['1'];
            Storage::disk('s3')->delete($deleteImage->file);

            $rekognitionClient = $this->configRekognitionClient();
            try {
                $rekognitionClient->deleteFaces(
                    [
                        'CollectionId' => $deleteImage->type,
                        'FaceIds' => [$deleteImage->face_rekognition_id],
                    ]
                );

            } catch (RekognitionException $ex) {
                ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
            }

            DB::table('image_faces')->where('id', $id)->delete();
            return ResponseService::responseJson(200, null, trans('messages.mes.delete_success'));
        }
    }

    private function getInfoImage(array $attributes)
    {
        $rekognitionClient = $this->configRekognitionClient();
        $createEmotions = [];
        if (request()->hasFile('file')) {
            // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
            $checkImageMustOne = $rekognitionClient->detectFaces(
                [
                    'Image' => [
                        'Bytes' => file_get_contents($attributes['file']),
                    ],
                    'Attributes' => ['EMOTIONS'],
                ]
            );
            // Ảnh chỉ được phép một người
            if (count($checkImageMustOne['FaceDetails']) != 1) {
                return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
            }
            $createEmotions = $checkImageMustOne['FaceDetails'][0]['Emotions'];
            $result = [];
            try {
                $result = $rekognitionClient->searchFacesByImage(
                    [
                        'CollectionId' => "WithoutMask",
                        'Image' => [
                            'Bytes' => file_get_contents($attributes['file']),
                        ],
                    ]
                );
            } catch (RekognitionException $ex) {
                // Nếu không có lỗi thì tìm kiếm trong Collection WithMask
                try {
                    $result = $rekognitionClient->searchFacesByImage(
                        [
                            'CollectionId' => "WithMask",
                            'Image' => [
                                'Bytes' => file_get_contents($attributes['file']),
                            ],
                        ]
                    );
                } catch (RekognitionException $ex) {
                    return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
                }
            }
        } else {
            // Chuyển đổi dữ liệu Base64 thành định dạng binary
            $imageData = $attributes['file'];

            // Loại bỏ phần khai báo định dạng ảnh
            $imageData = preg_replace('/^data:image\/\w+;base64,/', '', $imageData);

            // Giải mã chuỗi base64 thành dữ liệu binary
            $imageData = base64_decode($imageData);

            // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
            $checkImageMustOne = $rekognitionClient->detectFaces(
                [
                    'Image' => [
                        'Bytes' => $imageData,
                    ],
                    'Attributes' => ['EMOTIONS'],
                ],
        );
            // Ảnh chỉ được phép một người
            if (count($checkImageMustOne['FaceDetails']) != 1) {
                return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
            }
            $createEmotions = $checkImageMustOne['FaceDetails'][0]['Emotions'];
            $result = [];
            try {
                $result = $rekognitionClient->searchFacesByImage(
                    [
                        'CollectionId' => "WithoutMask",
                        'Image' => [
                            'Bytes' => $imageData,
                        ],
                    ]
                );
            } catch (RekognitionException $ex) {
                // Nếu không có lỗi thì tìm kiếm trong Collection WithMask
                try {
                    $result = $rekognitionClient->searchFacesByImage(
                        [
                            'CollectionId' => "WithMask",
                            'Image' => [
                                'Bytes' => $imageData,
                            ],
                        ]
                    );
                } catch (RekognitionException $ex) {
                    return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getAwsErrorMessage(), $ex->getAwsErrorMessage());
                }
            }
        }
        if ($result->get("FaceMatches") == []) {
            return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.image_face.face_compare_not_found'), trans('api.image_face.face_compare_not_found'));
        }
        $faceId = $result->get("FaceMatches")[0]["Face"]["FaceId"];
        $image = $this->model->where("face_rekognition_id", $faceId)->first();
        if ($image == null) {
            return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.image_face.face_compare_not_found'), trans('api.image_face.face_compare_not_found'));
        }
        $user = User::find($image->user_id);

        if ($user == null) {
            return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.user.login.false'));
        }

        if (!$user->getRoleVFace($user)) {
            return ResponseService::responseJsonError(Response::HTTP_NOT_FOUND, trans('api.user.login_not_granted'));
        }
        return ResponseService::responseJson(CODE_SUCCESS, compact('user', 'image', 'createEmotions'));
    }

    public function compareFace(array $attributes)
    {
        $timeNow = Carbon::now()->format('H:i:s');
        $now = Carbon::now();

        $dataImage = $this->getInfoImage($attributes);
        if($dataImage->original['code'] != CODE_SUCCESS) {
            return $dataImage;
        }
        $dataImage = $dataImage->original['data'];
        $user = $dataImage['user'];
        $image = $dataImage['image'];
        $createEmotions = $dataImage['createEmotions'];

        $dateNow = Carbon::now()->format('Y-m-d');
        $morning = Carbon::parse('12:00')->format('H:i:s');
        $afternoon = Carbon::parse('13:30')->format('H:i:s');
        $isCheckIn = false;
        $isCheckOut = false;
        $checkInInfo = ArrivingReport::query()
            ->whereDate("in_time", $dateNow)
            ->where("user_id", $user->id)
            ->where("type_date", config('analytic.type.work'))
            ->whereNotNull('in_time')
            ->whereNull('out_time')
            ->first();
        switch ($attributes['time']) {
            case 'in':
                // Kiểm tra nhân viên này hôm nay đã check in chưa?
                $arrivingIn_time = ArrivingReport::query()
                    ->whereDate("in_time", $dateNow)
                    ->where("user_id", $user->id)
                    ->when($timeNow < $morning, function ($e) use($morning){
                        $e->whereTime("in_time", "<", $morning);
                    }, function ($e) use ($morning) {
                        $e->whereTime('in_time', '>=', $morning);
                    })->first();

                if ($arrivingIn_time) {
                    $isCheckIn = true;
                } else {
                    if($checkInInfo) {
                        return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.arriving_report.need_check_out'), trans('api.arriving_report.need_check_out'));
                    }

                    $arrivingIn_time = new ArrivingReport();
                    $arrivingIn_time->in_time = $now;
                    $late = 0;
                    if($now->hour < 12 && $now->between($now->copy()->setHour(9)->setMinute(1), $now->copy()->setHour(18)->setMinute(0))) {
                        $late = 1;
                    }
                    $arrivingIn_time->late = $late;
                    $arrivingIn_time->user_id = $user->id;
                    $arrivingIn_time->link_face_in = $image->file;
                    if (request()->hasFile('file')) {
                        $arrivingIn_time->link_check_in = $this->saveImageFileForAWSs3($attributes['file'], "CheckIn");
                    } else {
                        $arrivingIn_time->link_check_in = $this->saveImage64ForAWSs3($attributes['file'], "CheckIn", $user->name);
                    }
                    $arrivingIn_time->type_date = 1;
                    $arrivingIn_time->status = 1;
                    $arrivingIn_time->created_at = Carbon::now();
                    if (array_key_exists("registration_type", $attributes)) {
                        $arrivingIn_time->registration_type = $attributes['registration_type'];
                    }
                    $arrivingIn_time->save();
                    $this->saveEmotion($createEmotions, $arrivingIn_time->id, $user->id, 'in');
                }
                break;
            case 'out':
                // Kiểm tra nhân viên này hôm nay đã check out chưa?
                $arrivingOut_time = ArrivingReport::query()
                    ->whereDate("out_time", $dateNow)
                    ->where("user_id", $user->id)
                    ->when($timeNow <= $afternoon, function ($e) use ($afternoon) {
                        $e->whereTime("out_time", "<=", $afternoon);
                    }, function ($e) use ($afternoon) {
                        $e->whereTime('out_time', '>=', $afternoon);
                    })->first();

                if ($arrivingOut_time) {
                    $isCheckOut = true;
                } else {
                    if ($checkInInfo) {
                        $isCheckIn = true;
                        // Nếu tìm thấy ngày check in ngày hôm nay thì cập nhật
                        $arrivingOut_time = $checkInInfo;
                        $arrivingOut_time->user_id = $user->id;
                        $arrivingOut_time->out_time = $now;
                        $arrivingOut_time->link_face_out = $image->file;
                        if (request()->hasFile('file')) {
                            $arrivingOut_time->link_check_out = $this->saveImageFileForAWSs3($attributes['file'], "CheckOut");
                        } else {
                            $arrivingOut_time->link_check_out = $this->saveImage64ForAWSs3($attributes['file'], "CheckOut", $user->name);
                        }
                        $arrivingOut_time->type_date = 1;
                        $arrivingOut_time->status = 1;
                        $arrivingOut_time->updated_at = Carbon::now();
                        if (array_key_exists("registration_type", $attributes)) {
                            $arrivingOut_time->registration_type = $attributes['registration_type'];
                        }
                        $arrivingOut_time->save();
                        $this->saveEmotion($createEmotions, $arrivingOut_time->id, $user->id, 'out');
                    } else {
                        return ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST,trans('api.arriving_report.need_check_time_in'), trans('api.arriving_report.need_check_time_in'));
                    }
                }
                break;
        }

        try {
            $token = JWTAuth::fromUser($user);
            $user->jwt_active = $token;
            $user->save();
        } catch (Exception $ex) {
            return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getMessage());
        }

        return ResponseService::responseJson(200, [
            'access_token' => "Bearer " . $token,
            'profile' => new UserResource($user),
            'in_time' => @$arrivingIn_time,
            'is_check_in' => $isCheckIn,
            'out_time' => @$arrivingOut_time,
            'is_check_out' => $isCheckOut,
            'imageLink' => config('services.aws.urlImage') . $image->file
        ]);
    }

    public function saveImageFileForAWSs3($file, $folder)
    {
        $name = time() . $file->getClientOriginalName();
        $filePath = $folder . '/' . $name;
        Storage::disk('s3')->put($filePath, file_get_contents($file));
        return $filePath;
    }

    public function saveImage64ForAWSs3($base64String, $folder, $nameStaff)
    {
        $image = base64_decode(preg_replace('/^data:image\/\w+;base64,/', '', $base64String));
        $name = time() . Str::slug($nameStaff, '') . '.jpg';
        $filePath = $folder . '/' . $name;
        Storage::disk('s3')->put($filePath, $image);
        return $filePath;
    }

    public function saveEmotion($createEmotions, $arriving_id, $user_id, $type_check)
    {
        $emotion = new Emotion();
        $emotion->user_id = $user_id;
        $emotion->arriving_id = $arriving_id;
        $emotion->time = Carbon::now();
        $emotion->type_check = $type_check;
        foreach ($createEmotions as $createEmotion) {
            switch ($createEmotion['Type']) {
                case "CALM":
                    $emotion->calm = $createEmotion['Confidence'];
                    break;
                case "SURPRISED":
                    $emotion->surprised = $createEmotion['Confidence'];
                    break;
                case "FEAR":
                    $emotion->fear = $createEmotion['Confidence'];
                    break;
                case "SAD":
                    $emotion->sad = $createEmotion['Confidence'];
                    break;
                case "CONFUSED":
                    $emotion->confused = $createEmotion['Confidence'];
                    break;
                case "DISGUSTED":
                    $emotion->disgusted = $createEmotion['Confidence'];
                    break;
                case "HAPPY":
                    $emotion->happy = $createEmotion['Confidence'];
                    break;
                case "ANGRY":
                    $emotion->angry = $createEmotion['Confidence'];
                    break;
            }
        }
        $emotion->created_at = new DateTime('now');
        $emotion->save();
    }

    public function checkImage(array $attributes)
    {
        $rekognitionClient = $this->configRekognitionClient();
        try {
            // Kiểm tra đảm bảo ảnh chỉ có một người, nếu ảnh có từ 2 người trở lên thì báo lỗi
            $checkImageMustOne = $rekognitionClient->detectFaces(
                [
                    'Image' => [
                        'Bytes' => file_get_contents($attributes['file']),
                    ],
                ]
            );
            // Ảnh chỉ được phép một người
            if (count($checkImageMustOne['FaceDetails']) != 1) {
                ResponseService::responseJsonError(Response::HTTP_BAD_REQUEST, trans('api.image_face.must_one_person'), trans('api.image_face.must_one_person'));
            }
            return ResponseService::responseJson(200, [
                'checkImage' => count($checkImageMustOne['FaceDetails']) == 1,
            ]);
        } catch (Exception $ex) {
            return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getMessage());
        }
    }

    public function checkIpAddress(array $attributes)
    {
        return ResponseService::responseJson(200, [
            'data' => UserSystemInfoHelper::get_ip()
        ]);
    }

    public function sendMailNegative()
    {
        $startDate = Carbon::now()->subDays(5)->startOfDay()->toDateString();
        $endDate = Carbon::now()->endOfDay()->addDays()->toDateString();

        // kiểm tra ngày hôm nay với đếm 5 ngày trước xem số sad và angry
        $results = DB::table(DB::raw('(
      SELECT user_id, COUNT(angry) as countAngry, 0 as countSad, GROUP_CONCAT(arriving_id) as arriving_ids
      FROM emotions
      WHERE angry >= 50
          AND created_at BETWEEN ? AND ?
          AND emotions.deleted_at IS NULL
      GROUP BY user_id

      UNION ALL

      SELECT user_id, 0 as countAngry, COUNT(sad) as countSad, GROUP_CONCAT(arriving_id) as arriving_ids
      FROM emotions
      WHERE sad >= 50
          AND created_at BETWEEN ? AND ?
          AND emotions.deleted_at IS NULL
        GROUP BY user_id
    ) as subquery'))
            ->setBindings([$startDate, $endDate, $startDate, $endDate])
            ->select('user_id', 'arriving_ids', DB::raw('SUM(countAngry) as totalAngry'), DB::raw('SUM(countSad) as totalSad'))
            ->groupBy('user_id')
            ->get();

        foreach ($results as $result) {
            $checkSumNegative = $result->totalAngry + $result->totalSad;
            if ($checkSumNegative >= 5) {
                $array = explode(',', $result->arriving_ids);
                $data = [
                    'title' => 'Negative Staff',
                    'content' => $array
                ];

                $email = (new NegativeStaffMail($data))->to('nguyentungbachhalo@gmail.com');

                try {
                    Mail::send($email);
                } catch (Exception $ex) {
                    return ResponseService::responseJsonError(Response::HTTP_INTERNAL_SERVER_ERROR, $ex->getMessage());
                }
            }
        }
    }

    public function breakTime(array $attributes)
    {
        $time = Carbon::now()->format('H:i:s');
        $date = Carbon::now()->format('Y-m-d');

        $dataImage = $this->getInfoImage($attributes);
        if($dataImage->original['code'] != CODE_SUCCESS) {
            return $dataImage;
        }
        $dataImage = $dataImage->original['data'];
        $user = $dataImage['user'];
        $msg = '';
        switch ($attributes['time']) {
            case 'go_out':
                BreakTime::query()->create([
                    BreakTime::USER_ID => $user->id,
                    BreakTime::DATE => $date,
                    BreakTime::GO_OUT_TIME => $time
                ]);
                $msg = trans('api.arriving_report.go_out');
                break;
            case 'go_into':
                $breakTime = BreakTime::query()->where(BreakTime::USER_ID, $user->id)
                    ->where(BreakTime::DATE, $date)
                    ->orderByDesc('id')
                    ->first();
                if($breakTime) {
                    $breakTime->go_into_time = $time;
                    $breakTime->save();
                } else {
                    BreakTime::query()->create([
                        BreakTime::USER_ID => $user->id,
                        BreakTime::DATE => $date,
                        BreakTime::GO_INTO_TIME => $time
                    ]);
                }
                $msg = trans('api.arriving_report.go_into');
                break;
        }
        return ResponseService::responseJson(CODE_SUCCESS, $msg);
    }
}
