<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-07-10
 */

namespace Repository;

use App\Models\Emotion;
use App\Models\Policy;
use App\Models\VIAMUserPolicy;
use App\Repositories\Contracts\EmotionRepositoryInterface;
use App\Repositories\Contracts\PolicyRepositoryInterface;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;

class PolicyRepository extends BaseRepository implements PolicyRepositoryInterface
{

     public function __construct(Application $app)
     {
         parent::__construct($app);

     }

    /**
       * Instantiate model
       *
       * @param Emotion $model
       */

    public function model()
    {
        return Policy::class;
    }

    public function list($attributes)
    {
        if(@$attributes['page'] || @$attributes['per_page']) {
            return $this->model->paginate($attributes['per_page']);
        }
        return $this->model->select('id', 'name')->get();
    }

    public function update(array $attributes, $id)
    {
        if(in_array($id, POLICY_V_FACE_ID)) {
            return false;
        }
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        if(in_array($id, POLICY_V_FACE_ID)) {
            return false;
        }
        VIAMUserPolicy::query()->where(VIAMUserPolicy::POLICY_ID, $id)->delete();
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
