<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Exports\UserExport;
use App\Models\User;
use App\Repositories\Contracts\UserRepositoryInterface;
use Carbon\Carbon;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;

class UserRepository extends BaseRepository implements UserRepositoryInterface
{

     public function __construct(Application $app)
     {
         parent::__construct($app);

     }

    /**
       * Instantiate model
       *
       * @param User $model
       */

    public function model()
    {
        return User::class;
    }

  public function pagination($request)
  {
      $limit = is_null(request('per_page')) ? 15 : request('per_page');

      $data = $this->model->query()
        ->whereNull('deleted_at')
      ->FindByName($request)
      ->FindByRole($request);

      if ($limit > 0) {
        return $data->paginate($limit);
      }
      return $data->get();
  }

//    public function export($request){
//      $data = $this->pagination($request);
//      $fileName = "VFaceExport" . ".xlsx";
//      return (new UserExport($data))->download($fileName);
//    }

  public function create(array $attributes)
    {
      $attributes['created_at'] = Carbon::now();
      $attributes['password'] = bcrypt($attributes['password']);
      return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function update(array $attributes, $id)
    {
      $attributes['updated_at'] = Carbon::now();
      if ($attributes['password']){
        $attributes['password'] = bcrypt($attributes['password']);
      }
      return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }
}
