<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Models\HistoryEditReport;
use App\Models\RDSManager;
use App\Models\User;
use App\Repositories\Contracts\HistoryEditReportRepositoryInterface;
use App\Repositories\Contracts\RDSManagerRepositoryInterface;
use App\Repositories\Contracts\VIAMRDSRepositoryInterface;
use Aws\Rds\RdsClient;
use Aws\Ssm\SsmClient;
use Helper\Common;
use Helper\ResponseService;
use Illuminate\Http\Response;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use function Clue\StreamFilter\fun;

class VIAMRDSRepository extends BaseRepository implements VIAMRDSRepositoryInterface
{

    public function __construct(Application $app)
    {
        parent::__construct($app);

    }

    /**
     * Instantiate model
     *
     * @param RDSManager $model
     */

    public function model()
    {
        return RDSManager::class;
    }

    public function list()
    {
        dd('list');
        return parent::lists($column, $key); // TODO: Change the autogenerated stub
    }

    public function detail(array $attributes)
    {
        dd($attributes);
        dd('detail');
        return parent::lists($column, $key); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes)
    {
        dd('create');
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function update(array $attributes, $id)
    {
        dd('update');
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        dd('delete');
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
