<?php
/**
 * Created by PhpStorm.
 * User: cuongnt
 * Year: 2023-06-07
 */

namespace Repository;

use App\Models\HistoryEditReport;
use App\Models\RDSManager;
use App\Models\RDSPermission;
use App\Models\User;
use App\Repositories\Contracts\HistoryEditReportRepositoryInterface;
use App\Repositories\Contracts\RDSManagerRepositoryInterface;
use App\Repositories\Contracts\VIAMRDSRepositoryInterface;
use Aws\Rds\RdsClient;
use Aws\Ssm\SsmClient;
use Helper\Common;
use Helper\ResponseService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use function Clue\StreamFilter\fun;

class VIAMRDSRepository extends BaseRepository implements VIAMRDSRepositoryInterface
{

    public function __construct(Application $app)
    {
        parent::__construct($app);

    }

    /**
     * Instantiate model
     *
     * @param RDSManager $model
     */

    public function model()
    {
        return User::class;
    }

    public function list(array $attributes)
    {
        $rds_manager_id = $attributes['rds_manager_id'];
        $database_name = $attributes['database_name'];

        $data = $this->model
            ->select('id', 'name')
            ->with([
                'rdsManagers' => function ($query) use ($rds_manager_id) {
                    $query->select('rds_manager.id', 'rds_manager.name')
                        ->where('rds_manager.id', $rds_manager_id);
                },
                'databases' => function ($query) use ($database_name) {
                    $query->where('database.name', $database_name)
                        ->with('rdsPermissions:id,name,type');
                }
            ])->get();

        $countType = RDSPermission::query()->select('id', 'type', DB::raw('count(*) as total'))
            ->groupBy(RDSPermission::TYPE)
            ->pluck('total', 'type')->toArray();

        $arrayData = [];
        foreach ($data as $key => $value) {
            $arrayData[$key]['user_id'] = $value->id;
            $arrayData[$key]['username'] = $value->name;
            $arrayData[$key]['rds_manager_id'] = [];
            $arrayData[$key]['status'] = false;

            foreach ($value->rdsManagers as $manager) {
                $arrayData[$key]['rds_manager_id'] = $manager->id;
                $arrayData[$key]['status'] = true;
            }

            $arrayData[$key]['database_name'] = [];
            $arrayData[$key]['database_id'] = [];
            $arrayData[$key]['permission_id'] = [];
            $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_DATA]] = 0;
            $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_STRUCTURE]] = 0;
            $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_ADMINISTRATION]] = 0;
            $count[TYPE_RDS_PERMISSION_DATA] = 0;
            $count[TYPE_RDS_PERMISSION_STRUCTURE] = 0;
            $count[TYPE_RDS_PERMISSION_ADMINISTRATION] = 0;
            foreach ($value->databases as $database) {
                $arrayData[$key]['database_id'] = $database->id;
                $arrayData[$key]['database_name'] = $database->name;
                foreach ($database->rdsPermissions as $permission) {
                    $arrayData[$key]['permission_id'][] = $permission->id;
                    $type = $permission->type;
                    if ($type == TYPE_RDS_PERMISSION_ALL) {
                        $count[TYPE_RDS_PERMISSION_DATA] = $countType[TYPE_RDS_PERMISSION_DATA];
                        $count[TYPE_RDS_PERMISSION_STRUCTURE] = $countType[TYPE_RDS_PERMISSION_STRUCTURE];
                        $count[TYPE_RDS_PERMISSION_ADMINISTRATION] = $countType[TYPE_RDS_PERMISSION_ADMINISTRATION];
                    } else {
                        $count[$type]++;
                    }
                    $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_DATA]] = $count[TYPE_RDS_PERMISSION_DATA];
                    $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_STRUCTURE]] = $count[TYPE_RDS_PERMISSION_STRUCTURE];
                    $arrayData[$key]['count_' . TYPE_RDS_PERMISSION[TYPE_RDS_PERMISSION_ADMINISTRATION]] = $count[TYPE_RDS_PERMISSION_ADMINISTRATION];
                }
            }
        }
        return (new Common)->myPaginate($arrayData);
    }

    public function getListDatabase(array $attributes)
    {
        $databases = DB::select('SHOW DATABASES');
        $databaseNames = array_map('current', $databases);
        $data = [];

        foreach ($databaseNames as $databaseName) {
            $data[] =$databaseName;
        }
        return $data;
    }

    public function create(array $attributes)
    {
        dd('create');
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function update(array $attributes, $id)
    {
        dd('update');
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        dd('delete');
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
